services:
  - type: web
    name: binance-tracker-v2
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn web.app:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
    autoDeploy: false